Homework1
made-mlops-2022/evgeny_ivanov pull request #1
Opened 2022-10-18 06:58 UTC by tupiznak

0. Структура проекта основана на cookiecutter-data-science. Настроены hydra, dvc, mlflow (postgres). Для внешнего репозитория dvc использовался DAGhub. Все ноутбуки используют git-lfs.
1. далее расписана по пунктам "самооценка"
2. Сделан [ноутбук](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/notebooks/EDA.ipynb) с EDA, сделан [скрипт](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/data/make_eda.py) и [отчет](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/reports/EDA.html)
3. [ф-я](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/models/baseline/train_baseline_model.py) тренировки модели (описание в ридми)
4. [ф-я](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/models/baseline/test_predict_baseline_model.py) предсказания (описание в ридми) артефакты (сама модель) берется из предыдущего шага dvc
5. структура модульная
6. логгеры логгируют
7. [несколько](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/models/baseline/test_predict_baseline_model.py) [тестов](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/features/test_build_features.py)
8. в тестах используется используется [подвыборка](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/features/test_build_features.py#L28) исходных данных, т.к. не понял, зачем что-то иное?
9. [конфиги](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/conf)
10. [датаклассы](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/conf/config.py)
11. [трансформер](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/features/build_features.py#L18)
12. [зависимости](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/requirements.txt)
13. [CI](https://github.com/made-mlops-2022/evgeny_ivanov/actions)
14. [hydra](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/conf)
15. разворачиваю mlflow + postgres для Model Registry
16. логгирую [параметры](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/models/train_model.py#L19) и [метрики](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/models/baseline/train_baseline_model.py#L44)
17. регистрирую [модель](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/mlops_homework/models/baseline/train_baseline_model.py#L50) не понял какой скрин, пусть будет [такой](https://github.com/made-mlops-2022/evgeny_ivanov/tree/homework1/ml_project/reports/figures) 
18. [утилиты](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/setup.py#L11)
19. используется [dvc](https://github.com/made-mlops-2022/evgeny_ivanov/tree/homework1/.dvc)
20. есть [пайплайн](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework1/ml_project/dvc.yaml) нужно запускать не dvc repro, а dvc exp run, т.к. иначе не смог скрестить с hydra. если объясните как, будет супер

2022-11-06 16:49 UTC, SVizor42 commented on ml_project/mlops_homework/data/make_eda.py
> +    df = pd.read_csv("../../data/raw/heart_cleveland_upload.csv")
Почему просто не вынести эти пути в конфиг?

2022-11-06 16:51 UTC, SVizor42 commented on ml_project/mlops_homework/features/build_features.py
> +    df = pd.read_csv(DATA_PATH.joinpath('raw/heart_cleveland_upload.csv'))
Аналогично - было бы проще вынести путь до данных и моделей в файл конфига

2022-11-06 16:53 UTC, SVizor42 commented on ml_project/mlops_homework/features/build_features.py
> +    x_input = df.drop(columns=['condition'])
Таргет лучше не хардкодить. Лучше вынести в отдельный фича конфиг или хотя бы константы. С другими модулями аналогичная ситуация

2022-11-06 16:55 UTC, SVizor42 commented on ml_project/mlops_homework/features/test_build_features.py
> +import pytest
Стандартные модули импортируются до локальных

2022-11-06 16:56 UTC, SVizor42 commented on ml_project/mlops_homework/models/baseline/predict_baseline_model.py
> +def main(features_file, targets_file):
Typing?

2022-11-06 16:58 UTC, SVizor42 commented on ml_project/mlops_homework/models/baseline/train_baseline_model.py
> +    model = BaselineModel(penalty="l2", cv=cv, max_iter=10000, tol=0.01)
Эти параметры тоже лучше вынести в конфиг модели

2022-11-06 17:05 UTC, SVizor42 commented on ml_project/mlops_homework/features/build_features.py
> +class DataTransformer(BaseEstimator, TransformerMixin):
Думаю, можно было вынести класс трансформера в отдельный модуль

2022-11-06 17:19 UTC, SVizor42 commented on ml_project/mlops_homework/models/train_model.py
> +    if cfg.model.name == 'baseline':
Т.е. если модель с именем `baseline` не будет найдена в конфигах, то процедура обучения будет пропущена?

2022-11-06 17:22 UTC, SVizor42 requested changes
Интересная работа. Реализовано много пунктов. По некоторым моментам есть небольшие комментарии:

1. Структура - приведенный в README оргчарт не соответствует реальности. Плюс в ветке есть ненужные файлы (например, пустой `vizualize.py`, `Makefile`, который вроде не используется) - такое лучше не добавлять.
2. Тесты лучше вынести в отдельную папку `tests` и создать там `conftest.py` с общими фикстурами.
3. По п.8 (генерация данных). Здесь ожидается семплирование данных на основе распределений (например, полученных по итогам EDA) или использование приведенных библиотек для тестирования.
4. См. прочие комментарии по поводу конфигов, оставленные в модулях.

2022-11-13 17:08 UTC, tupiznak commented
1. Исправил ридми, убрал лишние файлы
2. Вынес тесты, создал conftest
3. Добавил faker в тест
4. Исправил остальное. А именно:

1. Выделил все пути в конфиг
2. Выделил таргет в конфиг
3. Импортировал стандартные модули до локальных
4. Добавил typing
5. Вынес параметры модели в конфиг
6. Вынес трансформер в модуль
7. Добавил else raise

2022-11-14 04:27 UTC, SVizor42 commented on ml_project/mlops_homework/models/baseline/train_baseline_model.py
> +    target = df["condition"]
Таргет остался

2022-11-14 04:32 UTC, SVizor42 commented on ml_project/mlops_homework/models/train_model.py
> +import dvc.api
Подними выше, пожалуйста

2022-11-14 04:54 UTC, SVizor42 approved these changes
Теперь ок. Зачёл все пункты.
Пару моментов на будущее:
* указывай для следующих ДЗ сумму баллов, которую ожидаешь получить;
* как предложение - "портянку" коммитов можно сжимать при помощи [git squash](https://medium.com/nuances-of-programming/%D0%BA%D0%B0%D0%BA-%D1%81%D0%B6%D0%B8%D0%BC%D0%B0%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D1%8B-%D0%B2-git-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-git-squash-8a84b9f62734).

Ветку можно сливать.

**Сумма: 40 баллов**

2022-11-14 11:39 UTC, merged