Homework3
made-mlops-2022/evgeny_ivanov pull request #3
Opened 2022-11-30 11:13 UTC by tupiznak

0. [docker compose](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/docker-compose.yaml) за основу взят офф файл
1. [generate](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/dags/generate.py)
2. [train](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/dags/train.py)
3. [predict](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/dags/predict.py)
4. все даги реализованы только с помощью DockerOperator. для каждого дага отдельные [контейнеры](https://github.com/made-mlops-2022/evgeny_ivanov/tree/homework3/airflow_ml_dags/docker)
5. всего 52б, вроде
6. [сенсор1](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/dags/train.py#L28) [сенсор2](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/dags/predict.py#L28)
7. [test](https://github.com/made-mlops-2022/evgeny_ivanov/tree/homework3/airflow_ml_dags/tests)
8. [mlflow](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/docker-compose.yaml#L87) взял докер из ДЗ 2, т.к. там настроено mlflow+s3
9. [сохранение](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/docker/train/train.py#L50) [загрузка](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/docker/predict/predict.py#L25)
10. [alert](https://github.com/made-mlops-2022/evgeny_ivanov/blob/homework3/airflow_ml_dags/docker-compose.yaml#L51)
скрины
![image](https://user-images.githubusercontent.com/17914777/204781434-6f93dfd2-c235-47b2-9886-8c17b01eb99c.png)
![image](https://user-images.githubusercontent.com/17914777/204781503-b6616d21-7340-4a4f-bb91-113362c4a6fd.png)
![image](https://user-images.githubusercontent.com/17914777/204781517-fa7697a7-2da4-4711-bddb-4f8195dc5a86.png)
![image](https://user-images.githubusercontent.com/17914777/204781537-324e74eb-f849-4a3f-b573-b910d1544300.png)

2022-12-04 14:40 UTC, bulaevvi requested changes
Приложите общий скриншот со списком всех дагов

2022-12-06 03:34 UTC, bulaevvi commented
См. пример в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-07 07:56 UTC, tupiznak commented
![image](https://user-images.githubusercontent.com/17914777/206120626-9bd42208-94e6-4141-9a3f-af98f3cc8b50.png)

2022-12-07 08:01 UTC, bulaevvi requested changes
Верхние три скриншота нормальные, но на последнем (общем) видно, что второй даг падал (судя по красному кружочку). Надо разобраться, почему он падал, и добиться такого результата, чтобы все выполнялось нормально

Обратите внимание, что в приведенном мною дискордовском примере падений не было

Прикрепите пожалуйста скриншот прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-07 10:28 UTC, bulaevvi commented
Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-07 17:36 UTC, tupiznak commented
![image](https://user-images.githubusercontent.com/17914777/206251498-b24f111e-8ac8-40ef-9ed7-15b03b37172a.png)
я просто вручную поставил на одном из запусков "ошибка", там же один из запусков был success. вот без ошибок

2022-12-08 04:23 UTC, bulaevvi approved these changes
Итого 32 балла. Делайте merge

2022-12-08 07:08 UTC, tupiznak commented
надо дождаться проверки второго дз, иначе pr не смогут посмотреть

2022-12-19 10:31 UTC, closed without merging